
name: Stock Bot Multi-source

on:
  schedule:
    - cron: "*/5 2-8 * * 1-5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: python bot_multi_source.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
<<<<<<< HEAD
          SYMBOLS: ${{ secrets.SYMBOLS }}
=======
          USE_VNSTOCK: '1'
>>>>>>> parent of 6f7af73 (trước chạy được, cấu hình lại timezone)
