name: NotifyStockTelegram
on:
  schedule:
    - cron: '*/5 9-15 * * 1-5'  # runs every 5 minutes, Mon-Fri, 9am-3pm UTC
  workflow_dispatch:  # allow manual run
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot.py
        run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
          # Optional: set USE_VNSTOCK=1 if you added vnstock secret/need it
          # USE_VNSTOCK: ${{ secrets.USE_VNSTOCK }}
